# Site settings
title:       PureCore.ro
email:       ogg@purecore.ro
author:      Valentin M. Padurean ("Ogg")
description: "Personal blog on Functional (Reactive) Programming, Scala, Haskell & more."
baseurl:     ""
url:         "http://purecore.ro"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:     purecorero

# Social icons
github_username:      padurean
bitbucket_username:
stackoverflow_id:
twitter_username:     vpadure
google_plus_id:       ValentinPadurean
linkedin_username:    vpadure
angellist_username:   valentin-m-padurean
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Sharing is caring :)'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: true
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
